knime-ip/knip

org.knime.knip.base/src/org/knime/knip/base/node/dialog/DataAwareDefaultNodeSettingsPane.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/ImgCanvas.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/LabelingEditorNodeDialog.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/control/LELabelingType.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/control/LabelingEditorChangeTracker.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/control/LabelingEditorManager.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/dialogcomponents/LabelingEditorLabelingRU.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/dialogcomponents/LabelingEditorView.java

Contains fixes for Issues #81, #71, #69, #68, #67 and various smaller improvements.

Interactive labeling editor bugfix

---

org.knime.knip.base/src/org/knime/knip/base/nodes/proc/maxfinder/MaximumFinderNodeFactory.xml

Improve MaximumFinder Node Description

---

org.knime.knip.io/src/org/knime/knip/io/nodes/imgwriter2/ImgWriter2NodeModel.java

Fail writing if a file already exists and overwrite is not enabled.

---

org.knime.knip.io/src/org/knime/knip/io/nodes/imgwriter2/ImgWriter2NodeModel.java

Update wording on the overwrite error message

---

org.knime.knip.tracking/.checkstyle
org.knime.knip.tracking/META-INF/MANIFEST.MF
org.knime.knip.tracking/res/KNIMECheckstyle5.0.xml
org.knime.knip.tracking/src/org/knime/knip/tracking/data/BitMaskCentroid.java
org.knime.knip.tracking/src/org/knime/knip/tracking/data/TrackedNode.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/TrackingNodeSetFactory.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/hiliter/TrackData.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/hiliter/TrackHilitePropagatorNodeModel.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/hiliter/TrackHilitePropagatorSettingsModels.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/laptracker/GenericLapTracker.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/laptracker/KNIPCostCalculator.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/laptracker/LAPTrackerNodeDialog.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/laptracker/LAPTrackerNodeFactory.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/laptracker/LAPTrackerNodeModel.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/laptracker/LAPTrackerSettingsModels.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/trackmate/TrackmateTrackerNodeDialog.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/trackmate/TrackmateTrackerNodeFactory.xml
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/trackmate/TrackmateTrackerNodeModel.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/trackmate/TrackmateTrackerSettingsModels.java

* Updated the TrackMate Version
* Fix #98 
* Fix broken checkstyle configuration

Trackmate fixes

---

org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader/ImgReaderNodeDialog.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader/ImgReaderNodeFactory.xml
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader/ImgReaderNodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader/ImgReaderSettingsModels.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader/ReadFileImgTable.java

Sprung from the discussion in #96

Add option to read metadata that is not supported by ome-xml

---

org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/dialogcomponents/DialogComponentLabelingEditorView.java

Fixed a bug in the InteractiveLabelingEditor causing the editor to reset saved changes when loading.

Small Bugfix

---

org.knime.knip.base/src/org/knime/knip/base/node/XMLNodeUtils.java
org.knime.knip.testing/src/org/knime/knip/base/nodes/testing/ImgComparatorNodeFactory.java
org.knime.knip.testing/src/org/knime/knip/base/nodes/testing/LabelingComparatorNodeFactory.java
org.knime.knip.testing/src/org/knime/knip/base/nodes/testing/TableCellViewer/TestTableCellViewNodeFactory.java

Hey @dietzc, 
this should fix the problems #137 caused with the tests. I made sure backwards compatibility is fixed and then moved 3 classes in tests to the new node descriptions.

Fixes for NodeDescription backwards compatability

---

org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/trackmate/TrackmateTrackerNodeDialog.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/trackmate/TrackmateTrackerNodeModel.java
org.knime.knip.tracking/src/org/knime/knip/tracking/nodes/trackmate/TrackmateTrackerSettingsModels.java
org.knime.knip.tracking/src/org/knime/knip/tracking/util/NodeTools.java

Trackmate tracker fix #155

---

org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader/FileChooserPanel.java

allow copying of path

---

org.knime.knip.io/src/org/knime/knip/io/nodes/imgwriter2/ImgWriter2.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgwriter2/ImgWriter2NodeDialog.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgwriter2/ImgWriter2NodeFactory.xml
org.knime.knip.io/src/org/knime/knip/io/nodes/imgwriter2/ImgWriter2NodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgwriter2/ImgWriter2SettingsModels.java

Inspired by #166 I added some improvements to the imagewriter.
See: https://github.com/knime-ip/knip/commit/875fafb672cd82163657891d18e9438bd89662a6

Imgwriter improvements

---

org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfromdialog/ImgReader2NodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfrominput/ImgReaderTableNodeModel.java

- Add warning to node state if errors occur during execution
- raise logvel of reading exceptions from warning to error.

Enhance visibility of Errors when reading images

---

org.knime.knip.base/META-INF/MANIFEST.MF
org.knime.knip.base/plugin.xml
org.knime.knip.base/src/org/knime/knip/base/data/KNIPCellFactory.java
org.knime.knip.base/src/org/knime/knip/base/data/img/ImgPlusCell.java
org.knime.knip.base/src/org/knime/knip/base/data/img/ImgPlusCellSerializer.java
org.knime.knip.base/src/org/knime/knip/base/data/labeling/LabelingCell.java
org.knime.knip.base/src/org/knime/knip/base/data/labeling/LabelingCellFactory.java
org.knime.knip.base/src/org/knime/knip/base/data/labeling/LabelingCellSerializer.java

we have to wait until KNIME fixed a bug in the serialization discovery.

DO NOT MERGE: Using new DataType Extension in KNIME to register Cells

---

org.knime.knip.base/src/org/knime/knip/base/nodes/io/imggenerator/ImgGeneratorNodeModel.java

add streaming to img generator

---

org.knime.knip.base/src/org/knime/knip/base/node/dialog/DialogComponentSubsetSelection2.java
org.knime.knip.base/src/org/knime/knip/base/node/nodesettings/SettingsModelSubsetSelection2.java
org.knime.knip.base/src/org/knime/knip/base/node/nodesettings/SubsetSelectionUtils.java
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/AlignerNodeFactory2.java
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/AlignerNodeFactory2.xml
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/ImgCropperNodeFactory2.java
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/ImgCropperNodeFactory2.xml
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/ProcNodeSetFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/seg/LabNodeSetFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/seg/LabelingOrthoCropperNodeFactory2.java
org.knime.knip.base/src/org/knime/knip/base/nodes/seg/LabelingOrthoCropperNodeFactory2.xml
org.knime.knip.io/src/org/knime/knip/io/nodes/imgimporter/ImgImporterNodeFactory.xml
org.knime.knip.io/src/org/knime/knip/io/nodes/imgimporter/ImgImporterNodeFactory2.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgimporter/ImgImporterNodeFactory2.xml
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/AbstractImgReaderNodeDialog.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/AbstractImgReaderNodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/AbstractReadImgFunction.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfromdialog/ReadImg2Function.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfrominput/ReadImgTableFunction.java

this pull request changes the way the subset selection model stores its selection. before the subset selection model stored the selected indices in an int array. now the subset selection stores its indices as a string. this allows for easy modification of the selected indices with flow variables as request in #146 .

change subset selection model from storing ints[] to storing strings

---

org.knime.knip.base/src/org/knime/knip/base/nodes/knimeimagebridge/PNGValueToImgPlusCellNodeFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/knimeimagebridge/PNGValueToImgPlusCellNodeFactory.xml

transparent values (alpha values = 255) can now be replaced with a customizable value.
see issue #93 .

add replace transparent values with functionality.

---

org.knime.knip.io/src/org/knime/knip/io/ImgSource.java
org.knime.knip.io/src/org/knime/knip/io/ScifioImgSource.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/AbstractImgReaderNodeDialog.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/AbstractImgReaderNodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/AbstractReadImgFunction.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfromdialog/ImgReader2NodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfromdialog/ReadImg2Function.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfrominput/ImgReaderTableNodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfrominput/ReadImgTableFunction.java

add support for predefined image types as requested in issue #79.

Img reader output type

---

org.knime.knip.base/src/org/knime/knip/base/nodes/metadata/setimgmetadata/SetImgMetadataNodeModel.java
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/imgjep/ImgJEPNodeModel.java

as requested in #195. Splitter is missing.

add streaming capabilities to img calculator and set img metadata node

---

org.knime.knip.base/src/org/knime/knip/base/nodes/filter/FilterNodeSetFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/filter/GaussNativeTypeNodeFactory2.java
org.knime.knip.base/src/org/knime/knip/base/nodes/filter/GaussNativeTypeNodeFactory2.xml

Now either a single sigma (which will be used for each dimension) or multiple sigmas (must match the number of selected dimensions) are supported.
See issue #94.

add support for multiple sigmas

---

org.knime.knip.base/src/org/knime/knip/base/data/CachedObjectAccess.java
org.knime.knip.base/src/org/knime/knip/base/data/StreamUtil.java
org.knime.knip.base/src/org/knime/knip/base/data/img/ImgPlusCell.java
org.knime.knip.base/src/org/knime/knip/base/data/img/ImgPlusCellFactory.java
org.knime.knip.base/src/org/knime/knip/base/data/labeling/LabelingCell.java

Refactor ImgPlusCell/LabelingCell

---

org.knime.knip.base/src/org/knime/knip/base/nodes/view/AbstractCellView.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/PlainCellView.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/TabbedCellView.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/imgparadjust/ImgParAdjustNodeView.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/imgparadjust/ParameterPanel.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/ImgCanvas.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/events/ImgViewerMouseMovedEvent.java

Adapted the Image Parameter Adjuster to the new views and squashed a bug in the Image Info Panel

ImageViewerAdjustments

---

org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/LabelingEditorNodeFactory.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/LabelingEditorNodeModel.java

Addresses: https://github.com/knime-ip/knip/issues/70
@AndreasBurger do my changes do the job? can you review and test?

Reuse incoming LabelingCell if nothing has changed

---

org.knime.knip.base/src/org/knime/knip/base/nodes/view/AbstractCellView.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/TableCellViewNodeView.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/imgparadjust/ImgParAdjustNodeView.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/segmentoverlay/SegmentOverlayNodeView.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/events/TablePositionEvent.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/TableOverviewPanel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/AbstractDefaultAnnotatorView.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/AnnotatorView.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/create/OverlayAnnotatorView.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/dialogcomponents/LabelingEditorView.java

All reworked viewers now display the current row and column name in the navigation bar. 
This implements #256

Table cell viewer enhancements

---

org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/MinimapAndPlaneSelectionPanel.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/PlaneSelectionPanel.java

Added some additional validation and fixed some minor layout issues. Fixes #271.

Fixed erroneous layouting of the planeselection panel

---

org.knime.knip.base/src/org/knime/knip/base/node/dialog/DialogComponentFilterSelection.java

I fixed a bug in the FilterSelectionDialog (remove button only worked once) and reworked the appearance of the dialog. 
@dietzc and @hornm could you have a look?
(Dialog is used in Segment Features Node -> Segment Settings Tab)

Rework filter selection dialog

---

org.knime.knip.base/src/org/knime/knip/base/nodes/proc/DimExtendNodeFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/ImgCropperNodeFactory2.java

Img minimum issue

---

org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/LabelOptionPanel.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/TransparencyColorSelectionPanel.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/TransparencyPanel.java

Fixed issue #316
Changed labels to improve clarity
Slightly changed layout to increase readability

Fixes and Layout Changes

---

org.knime.knip.base/src/org/knime/knip/base/nodes/knimeimagebridge/ConversionNodeSetFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/knimeimagebridge/PNGValueToImgPlusCell2NodeFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/knimeimagebridge/PNGValueToImgPlusCell2NodeFactory.xml

- Cleanup code
- Enhance node description

PNG to ImgPlus cleanup

---

org.knime.knip.base/plugin.xml
org.knime.knip.core/src/org/knime/knip/core/util/EnumUtils.java

Just a few things I noticed when working on #341

Small code cleanup

---

org.knime.knip.base/src/org/knime/knip/base/nodes/misc/splitter/SplitterNodeModel.java

Fix for https://github.com/knime-ip/knip/issues/235.
@beschu please review.

Splitter node

---

org.knime.knip.base/src/org/knime/knip/base/nodes/seg/graphcuts/GraphCutNodeFactory.java

@dietzc please take a look at the fix of this issue https://github.com/knime-ip/knip/issues/257.
There was some code in it which was never executed. Now the dialog behaviour is as expected.

Fix toggling between labeling/no-labeling.

---

org.knime.knip.features/src/org/knime/knip/features/DefaultFeatureService.java
org.knime.knip.features/src/org/knime/knip/features/FeatureService.java
org.knime.knip.features/src/org/knime/knip/features/groups/AbstractFeatureSetGroup.java
org.knime.knip.features/src/org/knime/knip/features/groups/ImgLabelingFeatureSetGroup.java
org.knime.knip.features/src/org/knime/knip/features/groups/PairedFeatureSetGroup.java
org.knime.knip.features/src/org/knime/knip/features/node/FeatureCalculatorDialogPane.java
org.knime.knip.features/src/org/knime/knip/features/node/FeatureCalculatorModel.java
org.knime.knip.features/src/org/knime/knip/features/node/model/SettingsModelFeatureSet.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/ColumnSelectionPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/DimensionSelectionPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/FeatureCalculatorSwingInputHarvester.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/FeatureCalculatorSwingInputPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/FeatureSetConfigPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/FeatureSetPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/FeatureSetSelectionPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/FilterOverlappingLabelsPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/FilterSegmentLabelsPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/LabelSettingsPanel.java
org.knime.knip.features/src/org/knime/knip/features/node/ui/SegmentSettingsPanel.java
org.knime.knip.features/src/org/knime/knip/features/sets/AbstractCachedFeatureSet.java
org.knime.knip.features/src/org/knime/knip/features/sets/Geometric2DFeatureSet.java

I did some general UI improvements.

Feature Calculator UI-Improvements

---

org.knime.knip.base/src/org/knime/knip/base/nodes/proc/ProcNodeSetFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/resizer/LabelingResizerNodeFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/resizer/LabelingResizerNodeFactory.xml

Adds LabelingResizer

---

org.knime.knip.base/src/org/knime/knip/base/data/ui/ViewerFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/io/kernel/ImgConfiguration.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/CombinedCellViewFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/view/segmentoverlay/SegmentOverlayNodeView.java
org.knime.knip.core/META-INF/MANIFEST.MF
org.knime.knip.core/src/org/knime/knip/core/awt/converter/RealColorARGBConverter.java
org.knime.knip.core/src/org/knime/knip/core/awt/converter/RealGreyARGBConverter.java
org.knime.knip.core/src/org/knime/knip/core/awt/converter/RealTableColorARGBConverter.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/ViewerComponents.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/ViewerMenuFactory.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/events/BrightnessContrastChgEvent.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/BrightnessContrastPanel.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/HistogramBC.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/providers/ImageRU.java
org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/panels/providers/ThresholdRU.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/create/OverlayAnnotatorView.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/deprecated/DialogComponentAnnotator.java
org.knime.knip.io/src/org/knime/knip/io/nodes/annotation/edit/dialogcomponents/LabelingEditorView.java

I cherry picked the commits from the brightness-contrast branch - just to stupid to merge the other one ;)

Cherry pick brightness contrast

---

org.knime.knip.io/src/org/knime/knip/io/ScifioImgSource.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/AbstractImgReaderNodeDialog.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/ColumnCreationMode.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfromdialog/ImgReader2NodeFactory.xml
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfromdialog/ImgReader2NodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfrominput/ImgReaderTableNodeDialog.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfrominput/ImgReaderTableNodeFactory.xml
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfrominput/ImgReaderTableNodeModel.java
org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader2/readfrominput/ReadImgTableFunction.java

Imgreader fixes

---

org.knime.knip.base/src/org/knime/knip/base/nodes/proc/Rotation2DNodeFactory.java

@dietzc  @hornm @tibuch @gab1one 
See title.
Issue #277

Added possibility to choose between radian and degree.

---

org.knime.knip.base/src/org/knime/knip/base/nodes/misc/splitter/Splitter2NodeDialog.java
org.knime.knip.base/src/org/knime/knip/base/nodes/misc/splitter/Splitter2NodeFactory.java
org.knime.knip.base/src/org/knime/knip/base/nodes/misc/splitter/Splitter2NodeFactory.xml
org.knime.knip.base/src/org/knime/knip/base/nodes/misc/splitter/Splitter2NodeModel.java
org.knime.knip.base/src/org/knime/knip/base/nodes/misc/splitter/Splitter2NodeSettings.java
org.knime.knip.base/src/org/knime/knip/base/nodes/proc/ProcNodeSetFactory.java

- adds column creation mode dropdown
- fixes wording in dialog

Splitter node improvements, fix #266

---

org.knime.knip.base/src/org/knime/knip/base/nodes/seg/cropper/SegmentCropperNodeDialog.java
org.knime.knip.base/src/org/knime/knip/base/nodes/seg/cropper/SegmentCropperNodeModel.java
org.knime.knip.base/src/org/knime/knip/base/nodes/seg/cropper/SegmentCropperNodeSettings.java

Various cleanups to improve the readability of the **Segment Cropper** node

 Cleanup code of the SegmentCropper Node

---

org.knime.knip.core/src/org/knime/knip/core/awt/AWTImageTools.java

Thumbnails of 3D images with channels are not rendered in colored in table view
- just to make sure that I didn't screw anything

FIXED Issue #450

---

org.knime.knip.base/src/org/knime/knip/base/nodes/proc/imgjep/ImgJEPNodeFactory.xml

Mention the user's responsibility wrt to the output types.
See #471.

ImgCalculator: improve documentation on types

---

org.knime.knip.cellviewer/src/org/knime/knip/cellviewer/CellNodeView.java
org.knime.knip.cellviewer/src/org/knime/knip/cellviewer/CellViewsManager.java
org.knime.knip.core/src/org/knime/knip/core/util/waitingindicator/libs/AbstractAnimatedIcon.java

Fixes some minor GUI bugs that resulted in uncaught Exceptions being thrown.
Additionally I cleaned up the affected classes a bit.

Cell view fixes & code cleanups
